# Generated by Django 2.0.5 on 2021-07-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20210721_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
