# Generated by Django 2.0.5 on 2021-07-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_remove_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
